src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Image")
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        $this->setSlug($this->title);
        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    private function setSlug(string $slug): self
    {
        $string = strtolower($slug);
        //Make alphanumeric (removes all other characters)
        $string = preg_replace("/[^a-z0-9_\s-]/", "", $string);
        //Clean up multiple dashes or whitespaces
        $string = preg_replace("/[\s-]+/", " ", $string);
        //Convert whitespaces and underscore to dash
        $string = preg_replace("/[\s_]/", "-", $string);

        $this->slug = $string;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function toArray() {
        $image = $this->getImage();
        return [
            'id' =>  $this->getId(),
            'title' =>  $this->getTitle(),
            'content' =>  $this->getContent(),
            'image' => $image ? $image->toArray() : null,
        ];
    }
}

src/Controller/BlogController.php
<?php


namespace App\Controller;

use App\Entity\Post;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BlogController extends AbstractController
{
    public function list() {
        $repository = $this->getDoctrine()->getRepository(Post::class);
        $posts = $repository->findAllSorted();

        return $this->render('blog/blog_list.html.twig', ['posts' => $posts]);
    }

    public function show(Post $post) {
        $repository = $this->getDoctrine()->getRepository(Post::class);
        $posts = $repository->findAllExcept($post->getId());

        return $this->render('blog/blog_detail.html.twig', ['post' => $post, 'recent' => $posts]);
    }
}

templates/blog/blog_detail.html.twig
{% extends 'base.html.twig' %}
{% block title %}Blog - {{ post.title }}{% endblock %}
{% block body %}
    <div class="columns is-centered">
        <div class="column is-7-tablet">
            <article class="blog-detail">
                {% if post.image | default(null) %}
                <figure class="blog-detail__thumb">
                    <img src="/uploads/{{ post.image.path }}" alt="{{ post.title }}">
                </figure>
                {% endif %}
                <h1 class="title is-2">{{ post.title }}</h1>
                <div class="blog-detail__meta">
                    <span class="meta-item has-text-accent"><b>{{ post.author.email }}</b></span>
                    <span class="meta-item">{{ post.createdAt | date("d/m/Y") }}</span>
                </div>
                {% if app.user %}
                <div class="blog-detail__actions">
                    <a href="{{ path('posts_edit', {'id': post.id}) }}" class="button">Editar</a>
                </div>
                {% endif %}
                <hr>
                <section class="content">
                    {{ post.content | raw }}
                </section>
                <hr>
            </article>
        </div>
        <div class="column is-7-tablet">
            <div class="columns">
                <div class="column is-12">
                    <h2 class="title is-4">Entradas recientes</h2>
                </div>
                {% for post in recent %}
                    <div class="column is-4">
                        {% include 'includes/blog_item.html.twig' %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/blog_list.html.twig
{% extends 'base.html.twig' %}
{% block title %}Blog{% endblock %}
{% block body %}
    <div class="columns">
        <div class="column is-12">
            <h1 class="title">Blog</h1>
        </div>
    </div>
    <div class="columns">
        {% for post in posts %}
            <div class="column is-3">
                {% include 'includes/blog_item.html.twig' %}
            </div>
        {% endfor %}
    </div>
{% endblock %}